AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: Environment name (dev/qa/prod)
  pBranchName:
    Description: "Branch Name(all lowercase, no symbols or spaces)"
    Type: String
  pArtifactsBucket:
    Description: "Artifact Bucket (all lowercase, no symbols or spaces)"
    Type: String
  pAWSRegion:
    Description: "Aws region (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountId:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pAWSAccountOpt:
    Description: "Aws account optimizador Id(all lowercase, no symbols or spaces)"
    Type: String
  pAccountName:
    Description: "Aws account (all lowercase, no symbols or spaces)"
    Type: String
  pTeamName:
    Description: "team Name (all lowercase, no symbols or spaces)"
    Type: String
  pRDAWSAccountId:
    Description: "Account Ruta Digital (all lowercase, no symbols or spaces)"
    Type: String
  pdeploymentDate:
    Description: "Date (all lowercase, no symbols or spaces)"
    Type: String

Resources:
  etaRole:
    Type: AWS::IAM::Role
    Condition: OnlyDev
    Properties:
      RoleName: !Sub "role-${pBranchName}"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - "arn:aws:iam::aws:policy/AmazonSNSFullAccess"
        - "arn:aws:iam::aws:policy/AmazonAthenaFullAccess"
        - "arn:aws:iam::aws:policy/SecretsManagerReadWrite"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: !Sub "${pTeamName}-access-to-s3-policy-bucketfile"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AccessToS3Policy
                Effect: Allow
                Action: s3:*
                Resource:
                  - !Sub "arn:aws:s3:::${pTeamName}-${pAccountName}-stage-file-${Stage}/*"
              - Sid: ReadSecretsManager
                Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                  - "secretsmanager:DescribeSecret"
                  - "secretsmanager:ListSecrets"
                Resource:
                  - !Sub "arn:aws:secretsmanager:${pAWSRegion}:${pAWSAccountId}:secret:*"
              - Sid: AccessTosqsPolicy
                Effect: Allow
                Action:
                  - "sqs:ReceiveMessage"
                  - "sqs:DeleteMessage"
                  - "sqs:GetQueueAttributes"
                  - "sqs:GetQueueUrl"
                  - "sqs:SendMessage"
                Resource: 
                  - "*"
              - Sid: AccessToLogsPolicy
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"
  
  daEtaSpLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "lambda-${pBranchName}"
      Description: "Lambda function Eta SimplyRoute"
      MemorySize: 2048
      Timeout: 900
      Code:
        ZipFile: |
          import json

          def handler(event, context):
              print("Hola Mundo desde Lambda!")
              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Hola Mundo!",
                      "event": event
                  })
              }
      Role: !GetAtt etaRole
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          ENVIRONMENT: !Ref Stage
          REGION: !Ref pAWSRegion
  
  

  

