name: CloudFormation deploy

on:
  pull_request:
    types: [closed]
    branches:
      - develop/*
      - qa/*
      - prod/*
  push:
    branches:
      - develop/*

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      #name: "develop"
      name: ${{ contains(github.ref, "develop/") && "develop" || contains(github.ref, "qa/") && "qa" || contains(github.ref, "prod/") && "prod" }}
    
    permissions:
      id-token: write
      contents: read  
    env:
      ENVIRONMENT: ${{ contains(github.base_ref, 'develop/') && 'dev' || contains(github.base_ref, 'qa/') && 'qa' || contains(github.base_ref, 'prod/') && 'prod' }}
      REGION: "us-east-1"

    steps:
      - name: Set timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Define environment
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            base_ref_part="${{ github.base_ref }}"
          else
            base_ref_part="${{ github.ref_name }}"
          fi
          
          env_name="${base_ref_part%%/*}"
          
          # Convertimos a minúsculas y asignamos valores específicos
          if [[ "${env_name,,}" == "develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${env_name,,}" == "qa" ]]; then
            echo "ENVIRONMENT=qa" >> $GITHUB_ENV
          elif [[ "${env_name,,}" == "prod" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=${env_name,,}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Parameters File
        run: |
          if [[ "$ENVIRONMENT" == "dev" ]]; then
            echo "PARAMETERS_FILE=./parameters-dev.json" >> $GITHUB_ENV
            echo "TAG_FILE=./tags_dev.json" >> $GITHUB_ENV
          elif [[ "$ENVIRONMENT" == "qa" ]]; then
            echo "PARAMETERS_FILE=./parameters-qa.json" >> $GITHUB_ENV
            echo "TAG_FILE=./tags_qa.json" >> $GITHUB_ENV
          elif [[ "ENVIRONMENT" == "prod" ]]; then
            echo "PARAMETERS_FILE=./parameters-prod.json" >> $GITHUB_ENV
            echo "TAG_FILE=./tags_prod.json" >> $GITHUB_ENV
          fi
      
      - name: Load JSON into Environment Variables
        run: |
          for row in $(jq -c '.[]' $PARAMETERS_FILE); do
            key=$(echo $row | jq -r 'keys[0]')
            value=$(echo $row | jq -r '.[]')
            echo "${key}=${value}" >> $GITHUB_ENV
          done
          echo "Loaded variables from $PARAMETERS_FILE."
      
      - name: Validate Variables
        run: |
          echo "TEAM=$TEAM"
          echo "ENVIRONMENT=$ENVIRONMENT"
          echo "BRANCH_NAME=$BRANCH_NAME"
          echo "REPOSITORY_NAME=$REPOSITORY_NAME"
          echo "ARTIFACTORY_BUCKET=$ARTIFACTORY_BUCKET"
          echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID"
          echo "AWS_ACCOUNT_ID_OPT=$AWS_ACCOUNT_ID_OPT"
          echo "DB_STAGE=$DB_STAGE"
          echo "DB_ANALYTICS=$DB_ANALYTICS"
          echo "AWS_ACCOUNT=$AWS_ACCOUNT"
          echo "AWS_RUTADIGITAL_ID=$AWS_RUTADIGITAL_ID"

      - name: Process Tags
        run: |
          # Convertir el JSON a pares de clave=valor escapados
          JSON=$(cat $TAG_FILE)
          TAGS=$(echo "$JSON" | jq -r 'map("\(.Key)=\(.Value|gsub(" "; "_")|gsub("&"; "y"))") | join(" ")')
          echo "TAGS=${TAGS}" >> $GITHUB_ENV
          echo "Processed tags: ${TAGS}"
      
      #- name: Set BRANCH_NAME from ref
      #  run: |
      #    RAW_BRANCH="${{ github.ref_name }}"
      #    CLEAN_BRANCH="${RAW_BRANCH#*/}" 
      #    echo "BRANCH_NAME=$CLEAN_BRANCH" >> $GITHUB_ENV

      - name: Set dynamic STACK_NAME
        run: echo "STACK_NAME=da-${BRANCH_NAME}-ecodistribucion" >> $GITHUB_ENV


      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          role-session-name: darolesession
          aws-region: "us-east-1"


      - name: Deploy template clouformation
        id: BRANCH_NAME
        shell: bash
        run: |
          aws cloudformation deploy --template-file templates/template.yaml \
            --region $REGION \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --tags $TAGS \
            --parameter-overrides \
                pTeamName=$TEAM \
                Stage=$ENVIRONMENT \
                pBranchName=$BRANCH_NAME \
                pArtifactsBucket=$ARTIFACTORY_BUCKET \
                pAWSRegion=$REGION \
                pAWSAccountId=$AWS_ACCOUNT_ID \
                pAWSAccountOpt=$AWS_ACCOUNT_ID_OPT \
                pdbStageName=$DB_STAGE \
                pAccountName=$AWS_ACCOUNT \
                pdeploymentDate=$TIMESTAMP
          aws cloudformation describe-stack-events --stack-name $STACK_NAME --max-items 5

      - name: Load Lambdas from YAML
        id: load_lambdas
        run: |
          LAMBDAS=$(yq -o=json '.' deploy_parameters/lambdas.yaml | jq -c '.lambdas')
          echo "LAMBDAS=$LAMBDAS" >> $GITHUB_ENV

      - name: upload all Lambdas code
        run: |
          mkdir -p "$GITHUB_WORKSPACE/zip"

          echo "$LAMBDAS" | jq -c '.[]' | while read -r item; do
            LAMBDA_NAME=$(echo "$item" | jq -r '.name')
            LAMBDA_PATH=$(echo "$item" | jq -r '.path')
            ZIP_PATH="$GITHUB_WORKSPACE/zip/$LAMBDA_NAME.zip"

            echo "Processing Lambda: $LAMBDA_NAME from path: $LAMBDA_PATH"

            FULL_PATH=$(realpath "$GITHUB_WORKSPACE/$LAMBDA_PATH")
            echo "DEBUG: FULL_PATH='$FULL_PATH'"
            ls -la "$FULL_PATH" || echo "Warning: No se pudo listar el contenido."

            if [ ! -d "$FULL_PATH" ]; then
              echo "Error: La carpeta $FULL_PATH no existe. Saltando..."
              continue
            fi

            cd "$FULL_PATH"
            zip -r "$ZIP_PATH" ./*
            cd -

            echo "Uploading ZIP to S3..."
            aws s3 cp "$ZIP_PATH" "s3://$ARTIFACTORY_BUCKET/stage_lib/lambda/$LAMBDA_NAME/"

            echo "Updating AWS Lambda function..."
            aws lambda update-function-code \
              --function-name "$LAMBDA_NAME" \
              --s3-bucket "$ARTIFACTORY_BUCKET" \
              --s3-key "stage_lib/lambda/$LAMBDA_NAME/$LAMBDA_NAME.zip" \
              --region "${{ env.REGION }}" \
              --publish
          done
